import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PPI Bartin | Login",
  description: "Generated by create next app",
};

const LoginLayout = ({ children }: { children: React.ReactNode }) => {
  return <div>{children}</div>;
};

export default LoginLayout;
