import { Metadata } from "next";

export const metadata: Metadata = {
  title: "PPI Bartin | comlite profile",
  description: "Generated by create next app",
};

const CompleteProfileLayout = ({ children }: { children: React.ReactNode }) => {
  return <>{children}</>;
};

export default CompleteProfileLayout;
